# Generated by Django 4.2.2 on 2023-11-14 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='price',
        ),
        migrations.AddField(
            model_name='hotel',
            name='special_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=100)),
                ('decription', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('check_availability', models.BooleanField(default=True)),
                ('featured_images', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='hotels')),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hotel')),
            ],
        ),
    ]
