# Generated by Django 4.2.2 on 2023-11-14 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_hotel_price_hotel_special_offer_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='itemsimg',
            new_name='hotelimg',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='featured_images',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_image', models.ImageField(null=True, upload_to='rooms')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.rooms')),
            ],
        ),
    ]
