# Generated by Django 4.2.7 on 2023-11-15 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_rooms_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='decription',
            new_name='description',
        ),
    ]
