# Generated by Django 4.2.7 on 2023-11-15 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_decription_rooms_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachments',
            old_name='room_id',
            new_name='room',
        ),
    ]
