# Generated by Django 4.2.7 on 2023-11-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_customuser_is_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_booking_user',
            field=models.BooleanField(default=False),
        ),
    ]
