# Generated by Django 4.2.7 on 2023-11-19 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_bookinguserprofile_email_clientprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinguserprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
