# Generated by Django 4.2.7 on 2023-11-19 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_bookinguserprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='emirates',
            new_name='emirate',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='license_no',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='owner_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='sponsor_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='hotel_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hotel'),
        ),
    ]
