# Generated by Django 4.2.7 on 2023-11-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_emirate_clientprofile_emirate_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='hotel_name',
            new_name='hotel_id',
        ),
    ]
