# Generated by Django 4.2.7 on 2023-11-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='hotel_name',
            new_name='hotel',
        ),
    ]
