# Generated by Django 4.2.7 on 2023-12-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_hotel_name_rooms_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinguserprofile',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
