# Generated by Django 4.2.7 on 2024-01-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_bookinguserprofile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinguserprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='email',
        ),
    ]
